spring:
  config:
    import: optional:file:.env[.properties]
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false 
  application:
    name: manajement_magang
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties: 
  hibernate:
    dialect: org.hibernate.dialect.postgreSQLDialect
    format_sql: true

cloudflare:
  r2:
    bucket: ${CLOUDFLARE_R2_BUCKET:default-bucket}
    access-key: ${CLOUDFLARE_R2_ACCESS_KEY:default-access-key}
    secret-key: ${CLOUDFLARE_R2_SECRET_KEY:default-secret-key}
    endpoint: ${CLOUDFLARE_R2_ENDPOINT:https://dummy-account-id.r2.cloudflarestorage.com}
    region: ${CLOUDFLARE_R2_REGION:auto}